### ISSUE TITLE
platform.dist() no longer available in Python 3.8

### ISSUE THREAD

**Issue by odel4y** [KIT-MRT/mrt_cmake_modules#12]
Hi all!
Starting with Python 3.8, the dist function
https://github.com/KIT-MRT/mrt_cmake_modules/blob/ce7c854c48cb458cf55a238fcce4821396b695f1/scripts/generate_cmake_dependency_file.py#L145
was removed from the platform module. Catkin builds will thus fail. Suggested alternative by the [platform documentation](https://docs.python.org/3.7/library/platform.html#platform.linux_distribution) is the [distro](https://pypi.org/project/distro/) package.
Since the release of ROS Noetic Ninjemys', the target distribution is Ubuntu Focal with Python 3.8.
I would be thankful for a fix!

**Comment by poggenhans** [comment]
Thanks for reporting, we fixed this with 7b87b3b62f8c08af0a21dba87951e5ce464a7d2e using rospkg, because ROS uses that too to figure out the distribution.
