### ISSUE TITLE
Is python-argparse dependency still necessary?

### ISSUE THREAD

**Issue by kenji-miyake** [KIT-MRT/mrt_cmake_modules#15]
According to https://github.com/ros/rosdistro/blob/master/rosdep/python.yaml#L471-L498, it seems it's only for older distributions.

I think in most of the distributions that are currently supported, we can use `argparse` without installing any packages.

```sh
$ docker run --rm -it ubuntu:18.04 /bin/bash # or 16.04
# apt update && apt install -y python
# python
Python 2.7.17 (default, Apr 15 2020, 17:20:14) 
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import argparse
>>> 
```

I'm asking this because it causes an error when using `colcon-ros-bundle` to `mrt_cmake_modules`.
When `dependency.name` is `python-argparse`, `rule` and `package_name_list` will be `[]`, so an error happens.
https://github.com/colcon/colcon-ros-bundle/blob/master/colcon_ros_bundle/task/ros_bundle.py#L62-L66

Of course, I'll send an issue/PR to `colcon-ros-bundle`, but it would be helpful if you could remove this old dependency.

**Comment by poggenhans** [comment]
We were just trying to be correct, but since argparse seems to be part of the standard library in python 2.7 and above, I guess we can just remove it.

For `alpine`, it is even wrong, I just noticed. `py-argparse` actually installs python3.
