### ISSUE TITLE
Nodelet library name

### ISSUE THREAD

**Issue by BaltashovIlia** [KIT-MRT/mrt_cmake_modules#16]
Hi, 
I think that nodelet library name in README and documentation is wrong. 

It says that the  nodelet library name will be: “libexample_package_nodelet”. 

But depending on the folder structure I only get such names: 
“libexample_package-example_name-nodelet”
“libexample_package-example_package-nodelet”

I created a simple example to show this problem: https://github.com/BaltashovIlia/example_package

**Comment by poggenhans** [comment]
Thanks, seems the doc is not up-to-date there. Its correct for `add_nodelet` but incorrect for the rest. I'll fix that.

**Comment by BaltashovIlia** [comment]
Hi 
Thanks. 

I think the documentation needs to be regenerated as well. In README.md you have a link to the Cmake API documentation, and on the doc_improvements branch I still have:
> `The resulting entry in the nodelet_plugins.xml is thus: <library path=”lib/libexample_package_nodelet”>`  

URL to it:
https://htmlpreview.github.io/?https://github.com/KIT-MRT/mrt_cmake_modules/blob/doc_improvements/doc/generated_cmake_api.html#mrt-add-node-and-nodelet
