### ISSUE TITLE
Many libraries in one package

### ISSUE THREAD

**Issue by BaltashovIlia** [KIT-MRT/mrt_cmake_modules#17]
Hi, 

Do I understand correctly that with default mrt CmakeList in one package there can be only either one library or a lot of nodes/nodeletes? And to create more than one library in the package, I need to modify Cmake? In general, I already did this, I just want to understand if I'm correct.

**Comment by poggenhans** [comment]
Yes, that is correct.

The reasoning is that there is usually no benefit of having two separate libraries in a single package. They are usually used in combination anyways. And it would be hard to figure out if one of these libraries need to be linked to the other and in which order.

If things should be separeted, its more advisable to create separate library packages.

**Comment by BaltashovIlia** [comment]
Thanks for your answer
