### ISSUE TITLE
Finding libboost-python-dev in Ubuntu 20.04 (focal, Boost1.71)

### ISSUE THREAD

**Issue by PPeltzer** [KIT-MRT/mrt_cmake_modules#25]
Hello,
Judging from your [FindBoostPython.cmake](https://github.com/KIT-MRT/mrt_cmake_modules/blob/master/cmake/Modules/FindBoostPython.cmake) file, I can see that you are aware that it is quite troublesome to find the correct `libboost-python-dev` version depending on the Ubuntu/Python/Boost version combination. However, the current implementation is failing for default Ubuntu 20.04 systems (which are shipped with Boost 1.71). You can recreate the failure by running the `mrt_cmake _modules generate_cmakelists.py` script for a `package.xml` containing the following line:

```xml
  <depend>libboost-python-dev</depend>
 ```

Alternatively, directly invoking the following stripped CMake file:

```cmake
cmake_minimum_required(VERSION 3.5.1)
project(testpackage)

find_package(mrt_cmake_modules REQUIRED)
include(UseMrtStdCompilerFlags)
include(GatherDeps)

find_package(AutoDeps REQUIRED COMPONENTS mrt_cmake_modules libboost-python-dev)
```

will cause the following CMake error:

```console
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package):
  Could not find a package configuration file provided by "boost_python3"
  (requested version 1.71.0) with any of the following names:

    boost_python3Config.cmake
    boost_python3-config.cmake

  Add the installation prefix of "boost_python3" to CMAKE_PREFIX_PATH or set
  "boost_python3_DIR" to a directory containing one of the above files.  If
  "boost_python3" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/local/share/cmake-3.12/Modules/FindBoost.cmake:261 (find_package)
  /home/patrick/mrt_cmake_modules/cmake/Modules/FindBoostPython.cmake:39 (find_package)
  /home/patrick/mrt_cmake_modules/cmake/Modules/FindAutoDeps.cmake:198 (find_package)
  /home/patrick/mrt_cmake_modules/cmake/Modules/FindAutoDeps.cmake:253 (_find_dep)
  CMakeLists.txt:8 (find_package)
```

Interestingly, I can help locate the package by adding
```cmake
find_package(Boost COMPONENTS python)
```
right before the AutoDeps call. However, I'm trying to build the [lanelet2_interface_ros](https://github.com/coincar-sim/lanelet2_interface_ros) package; therefore I don't want to touch its CMakeLists.txt and neither the mrt_cmake subrepo. 

The following [Boost Issue](https://github.com/boostorg/boost_install/issues/31) should explain the issue - the *FindBoostPython.cmake* script searches for the `python3` component in line 39, which is not supported in Boost version 1.71 (and should be supported again in 1.73 according to this issue). Instead, a search for `python` without the suffix is preferable. 

I understand that the problem should therefore be fixed by upgrading Boost to 1.73; however, Ubuntu focal ships with 1.71 and the fix has apparently not been backported for over a year now. So I would like to ask if you could address this on your side? This would help a lot by avoiding to upgrade Boost or patch either the `lanelet2_interface_ros` or this subrepo.

Best regards,

Patrick

**Comment by PPeltzer** [comment]
A colleague of mine kindly hinted that this issue is not present for version 1.0.5. Indeed it looks like commit 7be4486ba5ac05f4101138ece8a53a7108ea41b2 in version 1.0.6 broke the support for Ubuntu 20.04.

**Comment by poggenhans** [comment]
I am using 20.04 as well and it is working fine there (in our CI too). For cmake below 3.15 the findscript should take this path which covers the `python3` quirks:

https://github.com/KIT-MRT/mrt_cmake_modules/blob/3aae3659fc92cd48781412341970613ba1bc7e21/cmake/Modules/FindBoostPython.cmake#L23-L28

Your stacktrace includes files belonging to an old, local cmake 3.12 installation (20.04 ships with 3.16). Can this be the cause?

**Comment by PPeltzer** [comment]
Thank you for your reply @poggenhans. This downgraded cmake version is a relict of an upgrade script written for Ubuntu 16.04 which I've overseen. As you said, it actually downgraded the cmake version now on 20.04. I can confirm that all works flawlessly with the default 20.04 setup; so this is solved. Thanks again!
