### ISSUE TITLE
Can we get a new bloom release for Jazzy to fix Geographiclib?

### ISSUE THREAD

**Issue by Timple** [KIT-MRT/mrt_cmake_modules#36]
Cool, can we get a new bloom release for Jazzy as well then? As currently it's in a broken state regarding Geographiclib.

_Originally posted by @Timple in https://github.com/KIT-MRT/mrt_cmake_modules/issues/34#issuecomment-2182608424_

**Comment by Timple** [comment]
We missed the jazzy sync :slightly_frowning_face: 
Can we get a release before the new sync?

**Comment by wep21** [comment]
@keroe friendly ping. Could you bump new version and create a new release?

**Comment by poggenhans** [comment]
Sorry for the delay. We created a new release but I'm lacking the permissions to also release it to jazzy: https://github.com/ros2-gbp/ros2-gbp-github-org/issues/574

**Comment by Timple** [comment]
Now you do :slightly_smiling_face: Would you mind giving it a retry?

**Comment by poggenhans** [comment]
Created https://github.com/ros/rosdistro/pull/42484, https://github.com/ros/rosdistro/pull/42485, https://github.com/ros/rosdistro/pull/42486

**Comment by Timple** [comment]
That's three distros. But I was hoping for Jazzy 😃 
As that's the one that was broken...
