### ISSUE TITLE
Python3 Compatibility

### ISSUE THREAD

**Issue by JWhitleyAStuff** [KIT-MRT/mrt_cmake_modules#5]
Is there any plan to support Python3 with this package? Python2.7 updates end in January of 2020 and Autoware currently uses Python3 by default so building this package fails.

**Comment by poggenhans** [comment]
It is supposed to work with python3. However the parser seems to be more restrictive and complained about mixtures from tabs and spaces. I fixed that in 8abf7876ea82423145e4431f60ccfb194c55d999.

**Comment by JWhitleyAStuff** [comment]
Thanks, @poggenhans! I'm seeing strange things in our CI but they don't occur on my local build so it must be environment-specific. I'll let you know if I find any specific issue with this package.
